[profile.release]
debug = true
incremental = true
opt-level = 1

[package]
name = "egui_dock_testing"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.31"
egui = "0.31"
egui_dock = "0.16"
emath = "0.31"
tracy-client = "0.18.0"
toml = "0.8.20"