[profile.release]
debug = true
incremental = true
opt-level = 1

[package]
name = "egui_dock_testing"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.31"
egui = "0.31"
egui_dock = "0.16"
emath = "0.31"
tracy-client = "0.18.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
toml = "0.8.20"

# tracing = "0.1.37"
# tracing-subscriber = "0.3"
log = "0.4.27"
# # You only need serde if you want app persistence:
egui_extras = { version = "0.31.1", features = ["image", "all_loaders"] }
image = { version = "0.24.7", features = ["jpeg", "png", "gif"] }
# syntect = "5.0.0"
rfd = "0.15.3"
rand = "0.8.5"
# fs_extra = "1.3.0"
# duct = "0.13.6"
enum-iterator = "2.1.0"
# ra_ap_rust-analyzer = "0.0.220"
ra_ap_ide = "0.0.273"
syn = { version = "2.0.25", features = ["full", "extra-traits", "parsing", "visit"] }
quote = "1.0.29"
proc-macro2 = "1.0.64"
prettyplease = "0.2.10"
# slotmap = "1.0.6"
# clap = { version = "4.3.19", features = ["derive"] }
usvg = "0.35.0"
# generate = "1.5.0"
# savefile-derive = "0.17.4"
# k_board = "1.2.2"
# git2 = "0.19.0"
