
name = "Feather nRF52832"
manufacturer = "Adafruit"
is_main_board = true
standard = "Feather"
cpu = "Cortex-M4"
ram = 64
flash = 512
required_crates = ["nRF52832-hal", "nrf52832-pac", "nb", "embedded-hal", "embedded-time", "cortex-m-rt", "cortex-m", "panic-halt"]
related_crates = ["smart-leds", "ws2812-pio"]
