extreme_bg_color = "#69d2e7"
faint_bg_color = "#a7dbd8"
code_bg_color = "#e0e4cc"
panel_fill = "#f38630"
window_fill = "#fa6900"
window_stroke_color = "#586e75"
hyperlink_color = "#839496"
warn_fg_color = "#839496"
error_fg_color = "#839496"
