extreme_bg_color = "#d9ceb2"
faint_bg_color = "#948c75"
code_bg_color = "#d5ded9"
panel_fill = "#7a6a53"
window_fill = "#99b2b7"
window_stroke_color = "#586e75"
hyperlink_color = "#839496"
warn_fg_color = "#839496"
error_fg_color = "#839496"
