extreme_bg_color = "#ffffff"
faint_bg_color = "#cbe86b"
code_bg_color = "#f2e9e1"
panel_fill = "#1c140d"
window_fill = "#cbe86b"
window_stroke_color = "#586e75"
hyperlink_color = "#839496"
warn_fg_color = "#839496"
error_fg_color = "#839496"
