extreme_bg_color = "#343838"
faint_bg_color = "#005f6b"
code_bg_color = "#008c9e"
panel_fill = "#00b4cc"
window_fill = "#00dffc"
window_stroke_color = "#586e75"
hyperlink_color = "#839496"
warn_fg_color = "#839496"
error_fg_color = "#839496"
