extreme_bg_color = "#fad089"
faint_bg_color = "#ff9c5b"
code_bg_color = "#f5634a"
panel_fill = "#ed303c"
window_fill = "#3b8183"
window_stroke_color = "#586e75"
hyperlink_color = "#839496"
warn_fg_color = "#839496"
error_fg_color = "#839496"
