extreme_bg_color = "#ff4242"
faint_bg_color = "#f4fad2"
code_bg_color = "#d4ee5e"
panel_fill = "#e1edb9"
window_fill = "#f0f2eb"
window_stroke_color = "#586e75"
hyperlink_color = "#839496"
warn_fg_color = "#839496"
error_fg_color = "#839496"
