extreme_bg_color = "#1b676b"
faint_bg_color = "#519548"
code_bg_color = "#88c425"
panel_fill = "#bef202"
window_fill = "#eafde6"
window_stroke_color = "#586e75"
hyperlink_color = "#839496"
warn_fg_color = "#839496"
error_fg_color = "#839496"
