extreme_bg_color = "#556270"
faint_bg_color = "#4ecdc4"
code_bg_color = "#c7f464"
panel_fill = "#ff6b6b"
window_fill = "#c44d58"
window_stroke_color = "#586e75"
hyperlink_color = "#839496"
warn_fg_color = "#839496"
error_fg_color = "#839496"
