extreme_bg_color = "#bcbdac"
faint_bg_color = "#cfbe27"
code_bg_color = "#f27435"
panel_fill = "#f02475"
window_fill = "#3b2d38"
window_stroke_color = "#586e75"
hyperlink_color = "#839496"
warn_fg_color = "#839496"
error_fg_color = "#839496"
