extreme_bg_color = "#452632"
faint_bg_color = "#91204d"
code_bg_color = "#e4844a"
panel_fill = "#e8bf56"
window_fill = "#e2f7ce"
window_stroke_color = "#586e75"
hyperlink_color = "#839496"
warn_fg_color = "#839496"
error_fg_color = "#839496"
