extreme_bg_color = "#f0d8a8"
faint_bg_color = "#3d1c00"
code_bg_color = "#86b8b1"
panel_fill = "#f2d694"
window_fill = "#fa2a00"
window_stroke_color = "#586e75"
hyperlink_color = "#839496"
warn_fg_color = "#839496"
error_fg_color = "#839496"
