extreme_bg_color = "#2a044a"
faint_bg_color = "#0b2e59"
code_bg_color = "#0d6759"
panel_fill = "#7ab317"
window_fill = "#a0c55f"
window_stroke_color = "#586e75"
hyperlink_color = "#839496"
warn_fg_color = "#839496"
error_fg_color = "#839496"
