extreme_bg_color = "#f04155"
faint_bg_color = "#ff823a"
code_bg_color = "#f2f26f"
panel_fill = "#fff7bd"
window_fill = "#95cfb7"
window_stroke_color = "#586e75"
hyperlink_color = "#839496"
warn_fg_color = "#839496"
error_fg_color = "#839496"
