extreme_bg_color = "#b9d7d9"
faint_bg_color = "#668284"
code_bg_color = "#2a2829"
panel_fill = "#493736"
window_fill = "#7b3b3b"
window_stroke_color = "#586e75"
hyperlink_color = "#839496"
warn_fg_color = "#839496"
error_fg_color = "#839496"
