extreme_bg_color = "#bbbb88"
faint_bg_color = "#ccc68d"
code_bg_color = "#eedd99"
panel_fill = "#eec290"
window_fill = "#eeaa88"
window_stroke_color = "#586e75"
hyperlink_color = "#839496"
warn_fg_color = "#839496"
error_fg_color = "#839496"
