extreme_bg_color = "#a3a948"
faint_bg_color = "#edb92e"
code_bg_color = "#f85931"
panel_fill = "#ce1836"
window_fill = "#009989"
window_stroke_color = "#586e75"
hyperlink_color = "#839496"
warn_fg_color = "#839496"
error_fg_color = "#839496"
