extreme_bg_color = "#774f38"
faint_bg_color = "#e08e79"
code_bg_color = "#f1d4af"
panel_fill = "#ece5ce"
window_fill = "#c5e0dc"
window_stroke_color = "#586e75"
hyperlink_color = "#839496"
warn_fg_color = "#839496"
error_fg_color = "#839496"
