extreme_bg_color = "#300030"
faint_bg_color = "#480048"
code_bg_color = "#601848"
panel_fill = "#c04848"
window_fill = "#f07241"
window_stroke_color = "#586e75"
hyperlink_color = "#839496"
warn_fg_color = "#839496"
error_fg_color = "#839496"
