extreme_bg_color = "#ab526b"
faint_bg_color = "#bca297"
code_bg_color = "#c5ceae"
panel_fill = "#f0e2a4"
window_fill = "#f4ebc3"
window_stroke_color = "#586e75"
hyperlink_color = "#839496"
warn_fg_color = "#839496"
error_fg_color = "#839496"
