extreme_bg_color = "#b6d8c0"
faint_bg_color = "#c8d9bf"
code_bg_color = "#dadabd"
panel_fill = "#ecdbbc"
window_fill = "#fedcba"
window_stroke_color = "#586e75"
hyperlink_color = "#839496"
warn_fg_color = "#839496"
error_fg_color = "#839496"
