extreme_bg_color = "#a8e6ce"
faint_bg_color = "#dcedc2"
code_bg_color = "#ffd3b5"
panel_fill = "#ffaaa6"
window_fill = "#ff8c94"
window_stroke_color = "#586e75"
hyperlink_color = "#839496"
warn_fg_color = "#839496"
error_fg_color = "#839496"
