extreme_bg_color = "#e8ddcb"
faint_bg_color = "#cdb380"
code_bg_color = "#036564"
panel_fill = "#033649"
window_fill = "#031634"
window_stroke_color = "#586e75"
hyperlink_color = "#839496"
warn_fg_color = "#839496"
error_fg_color = "#839496"
