extreme_bg_color = "#cc0c39"
faint_bg_color = "#e6781e"
code_bg_color = "#c8cf02"
panel_fill = "#f8fcc1"
window_fill = "#1693a7"
window_stroke_color = "#586e75"
hyperlink_color = "#839496"
warn_fg_color = "#839496"
error_fg_color = "#839496"
