extreme_bg_color = "#edebe6"
faint_bg_color = "#d6e1c7"
code_bg_color = "#94c7b6"
panel_fill = "#403b33"
window_fill = "#d3643b"
window_stroke_color = "#586e75"
hyperlink_color = "#839496"
warn_fg_color = "#839496"
error_fg_color = "#839496"
