extreme_bg_color = "#3a111c"
faint_bg_color = "#574951"
code_bg_color = "#83988e"
panel_fill = "#bcdea5"
window_fill = "#e6f9bc"
window_stroke_color = "#586e75"
hyperlink_color = "#839496"
warn_fg_color = "#839496"
error_fg_color = "#839496"
