extreme_bg_color = "#490a3d"
faint_bg_color = "#bd1550"
code_bg_color = "#e97f02"
panel_fill = "#f8ca00"
window_fill = "#8a9b0f"
window_stroke_color = "#586e75"
hyperlink_color = "#839496"
warn_fg_color = "#839496"
error_fg_color = "#839496"
