extreme_bg_color = "#5e3929"
faint_bg_color = "#cd8c52"
code_bg_color = "#b7d1a3"
panel_fill = "#dee8be"
window_fill = "#fcf7d3"
window_stroke_color = "#586e75"
hyperlink_color = "#839496"
warn_fg_color = "#839496"
error_fg_color = "#839496"
