extreme_bg_color = "#000000"
faint_bg_color = "#9f111b"
code_bg_color = "#b11623"
panel_fill = "#292c37"
window_fill = "#cccccc"
window_stroke_color = "#586e75"
hyperlink_color = "#839496"
warn_fg_color = "#839496"
error_fg_color = "#839496"
