extreme_bg_color = "#382f32"
faint_bg_color = "#ffeaf2"
code_bg_color = "#fcd9e5"
panel_fill = "#fbc5d8"
window_fill = "#f1396d"
window_stroke_color = "#586e75"
hyperlink_color = "#839496"
warn_fg_color = "#839496"
error_fg_color = "#839496"
