extreme_bg_color = "#f6f6f6"
faint_bg_color = "#e8e8e8"
code_bg_color = "#333333"
panel_fill = "#990100"
window_fill = "#b90504"
window_stroke_color = "#586e75"
hyperlink_color = "#839496"
warn_fg_color = "#839496"
error_fg_color = "#839496"
