extreme_bg_color = "#1b325f"
faint_bg_color = "#9cc4e4"
code_bg_color = "#e9f2f9"
panel_fill = "#3a89c9"
window_fill = "#f26c4f"
window_stroke_color = "#586e75"
hyperlink_color = "#839496"
warn_fg_color = "#839496"
error_fg_color = "#839496"
