extreme_bg_color = "#a1dbb2"
faint_bg_color = "#fee5ad"
code_bg_color = "#faca66"
panel_fill = "#f7a541"
window_fill = "#f45d4c"
window_stroke_color = "#586e75"
hyperlink_color = "#839496"
warn_fg_color = "#839496"
error_fg_color = "#839496"
