extreme_bg_color = "#5e9fa3"
faint_bg_color = "#dcd1b4"
code_bg_color = "#fab87f"
panel_fill = "#f87e7b"
window_fill = "#b05574"
window_stroke_color = "#586e75"
hyperlink_color = "#839496"
warn_fg_color = "#839496"
error_fg_color = "#839496"
