extreme_bg_color = "#594f4f"
faint_bg_color = "#547980"
code_bg_color = "#45ada8"
panel_fill = "#9de0ad"
window_fill = "#e5fcc2"
window_stroke_color = "#586e75"
hyperlink_color = "#839496"
warn_fg_color = "#839496"
error_fg_color = "#839496"
