extreme_bg_color = "#951f2b"
faint_bg_color = "#f5f4d7"
code_bg_color = "#e0dfb1"
panel_fill = "#a5a36c"
window_fill = "#535233"
window_stroke_color = "#586e75"
hyperlink_color = "#839496"
warn_fg_color = "#839496"
error_fg_color = "#839496"
