extreme_bg_color = "#8dccad"
faint_bg_color = "#988864"
code_bg_color = "#fea6a2"
panel_fill = "#f9d6ac"
window_fill = "#ffe9af"
window_stroke_color = "#586e75"
hyperlink_color = "#839496"
warn_fg_color = "#839496"
error_fg_color = "#839496"
