extreme_bg_color = "#2d2d29"
faint_bg_color = "#215a6d"
code_bg_color = "#3ca2a2"
panel_fill = "#92c7a3"
window_fill = "#dfece6"
window_stroke_color = "#586e75"
hyperlink_color = "#839496"
warn_fg_color = "#839496"
error_fg_color = "#839496"
