extreme_bg_color = "#eff3cd"
faint_bg_color = "#b2d5ba"
code_bg_color = "#61ada0"
panel_fill = "#248f8d"
window_fill = "#605063"
window_stroke_color = "#586e75"
hyperlink_color = "#839496"
warn_fg_color = "#839496"
error_fg_color = "#839496"
