extreme_bg_color = "#f1fdf5ff"
faint_bg_color = "#fffec7ff"
panel_fill = "#ff9d2eff"
window_fill = "#919167ff"
window_stroke_color = "#586e75ff"
warn_fg_color = "#839496ff"
hyperlink_color = "#839496ff"
code_bg_color = "#f56218ff"
error_fg_color = "#839496ff"
