extreme_bg_color = "#046d8b"
faint_bg_color = "#309292"
code_bg_color = "#2fb8ac"
panel_fill = "#93a42a"
window_fill = "#ecbe13"
window_stroke_color = "#586e75"
hyperlink_color = "#839496"
warn_fg_color = "#839496"
error_fg_color = "#839496"
