extreme_bg_color = "#a70267"
faint_bg_color = "#f10c49"
code_bg_color = "#fb6b41"
panel_fill = "#f6d86b"
window_fill = "#339194"
window_stroke_color = "#586e75"
hyperlink_color = "#839496"
warn_fg_color = "#839496"
error_fg_color = "#839496"
