extreme_bg_color = "#ffedbf"
faint_bg_color = "#f7803c"
code_bg_color = "#f54828"
panel_fill = "#2e0d23"
window_fill = "#f8e4c1"
window_stroke_color = "#586e75"
hyperlink_color = "#839496"
warn_fg_color = "#839496"
error_fg_color = "#839496"
