extreme_bg_color = "#4e4d4a"
faint_bg_color = "#353432"
code_bg_color = "#94ba65"
panel_fill = "#2790b0"
window_fill = "#2b4e72"
window_stroke_color = "#586e75"
hyperlink_color = "#839496"
warn_fg_color = "#839496"
error_fg_color = "#839496"
