extreme_bg_color = "#0ca5b0"
faint_bg_color = "#4e3f30"
code_bg_color = "#fefeeb"
panel_fill = "#f8f4e4"
window_fill = "#a5b3aa"
window_stroke_color = "#586e75"
hyperlink_color = "#839496"
warn_fg_color = "#839496"
error_fg_color = "#839496"
