extreme_bg_color = "#fcfef5"
faint_bg_color = "#e9ffe1"
code_bg_color = "#cdcfb7"
panel_fill = "#d6e6c3"
window_fill = "#fafbe3"
window_stroke_color = "#586e75"
hyperlink_color = "#839496"
warn_fg_color = "#839496"
error_fg_color = "#839496"
