extreme_bg_color = "#9cddc8"
faint_bg_color = "#bfd8ad"
code_bg_color = "#ddd9ab"
panel_fill = "#f7af63"
window_fill = "#633d2e"
window_stroke_color = "#586e75"
hyperlink_color = "#839496"
warn_fg_color = "#839496"
error_fg_color = "#839496"
