extreme_bg_color = "#aaff00"
faint_bg_color = "#ffaa00"
code_bg_color = "#ff00aa"
panel_fill = "#aa00ff"
window_fill = "#00aaff"
window_stroke_color = "#586e75"
hyperlink_color = "#839496"
warn_fg_color = "#839496"
error_fg_color = "#839496"
