extreme_bg_color = "#805841"
faint_bg_color = "#dcf7f3"
code_bg_color = "#fffcdd"
panel_fill = "#ffd8d8"
window_fill = "#f5a2a2"
window_stroke_color = "#586e75"
hyperlink_color = "#839496"
warn_fg_color = "#839496"
error_fg_color = "#839496"
