name = "Arduino Uno"
manufacturer = "Arduino"
is_main_board = true
board_type = "Main"
standard = "Arduino"
cpu = "Microchip AVR"
ram = 2
flash = 32
required_crates = ["avrdude", "avr-libc", "ravedude", "avr-gcc", "ufmt", "nb", "embedded-hal", "embedded-time", "panic-halt"]
related_crates = ["smart-leds", "ws2812-pio"]

[pinout]
interfaces = [
	{name = "GPIO", roles = ["Digital", "Analog", "Port"]},
	{name = "I2C", roles = [ "SDA", "SCL"], bus = true},
	{name = "SPI", roles = ["SCK", "MISO", "MOSI", "SS"], bus = true},
	{name = "UART", roles = ["TX", "RX"], bus = true}
]

[pinout.pin_block]
ranges = [
	{start = 24, end = 31, roles = ["Port"], alias_fmts = ["PD{}"]},
	{start = 8, end = 13, roles = ["Analog", "Port"], alias_fmts = ["A{}", "PC{}"]},
	{start = 8, end = 13, roles = ["Port"], alias_fmts = ["PB{}"]},
	{start = 8, end = 31, exclude = [14, 15, 16, 17], roles = ["Digital"], alias_fmts = ["D{}"]},
]
assignments = [
	{numbers = [31], roles = ["RX"]},
	{numbers = [30], roles = ["TX"]},

	{numbers = [21], roles = ["SS"]},
	{numbers = [20], roles = ["MOSI"]},
	{numbers = [19], roles = ["MISO"]},
	{numbers = [18], roles = ["SCK"]},

	{numbers = [12], roles = ["SDA"]},
	{numbers = [13], roles = ["SCL"]},
]
