extreme_bg_color = "#fe4365"
faint_bg_color = "#fc9d9a"
code_bg_color = "#f9cdad"
panel_fill = "#c8c8a9"
window_fill = "#83af9b"
window_stroke_color = "#586e75"
hyperlink_color = "#839496"
warn_fg_color = "#839496"
error_fg_color = "#839496"
