extreme_bg_color = "#3fb8af"
faint_bg_color = "#7fc7af"
code_bg_color = "#dad8a7"
panel_fill = "#ff9e9d"
window_fill = "#ff3d7f"
window_stroke_color = "#586e75"
hyperlink_color = "#839496"
warn_fg_color = "#839496"
error_fg_color = "#839496"
