extreme_bg_color = "#efffcd"
faint_bg_color = "#dce9be"
code_bg_color = "#555152"
panel_fill = "#2e2633"
window_fill = "#99173c"
window_stroke_color = "#586e75"
hyperlink_color = "#839496"
warn_fg_color = "#839496"
error_fg_color = "#839496"
