extreme_bg_color = "#413e4a"
faint_bg_color = "#73626e"
code_bg_color = "#b38184"
panel_fill = "#f0b49e"
window_fill = "#f7e4be"
window_stroke_color = "#586e75"
hyperlink_color = "#839496"
warn_fg_color = "#839496"
error_fg_color = "#839496"
