extreme_bg_color = "#ff4e50"
faint_bg_color = "#fc913a"
code_bg_color = "#f9d423"
panel_fill = "#ede574"
window_fill = "#e1f5c4"
window_stroke_color = "#586e75"
hyperlink_color = "#839496"
warn_fg_color = "#839496"
error_fg_color = "#839496"
