extreme_bg_color = "#99b898"
faint_bg_color = "#fecea8"
code_bg_color = "#ff847c"
panel_fill = "#e84a5f"
window_fill = "#2a363b"
window_stroke_color = "#586e75"
hyperlink_color = "#839496"
warn_fg_color = "#839496"
error_fg_color = "#839496"
