extreme_bg_color = "#655643"
faint_bg_color = "#80bca3"
code_bg_color = "#f6f7bd"
panel_fill = "#e6ac27"
window_fill = "#bf4d28"
window_stroke_color = "#586e75"
hyperlink_color = "#839496"
warn_fg_color = "#839496"
error_fg_color = "#839496"
