extreme_bg_color = "#00a8c6"
faint_bg_color = "#40c0cb"
code_bg_color = "#f9f2e7"
panel_fill = "#aee239"
window_fill = "#8fbe00"
window_stroke_color = "#586e75"
hyperlink_color = "#839496"
warn_fg_color = "#839496"
error_fg_color = "#839496"
