extreme_bg_color = "#ecd078"
faint_bg_color = "#d95b43"
code_bg_color = "#c02942"
panel_fill = "#542437"
window_fill = "#53777a"
window_stroke_color = "#586e75"
hyperlink_color = "#839496"
warn_fg_color = "#839496"
error_fg_color = "#839496"
