extreme_bg_color = "#351330"
faint_bg_color = "#424254"
code_bg_color = "#64908a"
panel_fill = "#e8caa4"
window_fill = "#cc2a41"
window_stroke_color = "#586e75"
hyperlink_color = "#839496"
warn_fg_color = "#839496"
error_fg_color = "#839496"
