extreme_bg_color = "#554236"
faint_bg_color = "#f77825"
code_bg_color = "#d3ce3d"
panel_fill = "#f1efa5"
window_fill = "#60b99a"
window_stroke_color = "#586e75"
hyperlink_color = "#839496"
warn_fg_color = "#839496"
error_fg_color = "#839496"
