extreme_bg_color = "#5d4157"
faint_bg_color = "#838689"
code_bg_color = "#a8caba"
panel_fill = "#cad7b2"
window_fill = "#ebe3aa"
window_stroke_color = "#586e75"
hyperlink_color = "#839496"
warn_fg_color = "#839496"
error_fg_color = "#839496"
