extreme_bg_color = "#8c2318"
faint_bg_color = "#5e8c6a"
code_bg_color = "#88a65e"
panel_fill = "#bfb35a"
window_fill = "#f2c45a"
window_stroke_color = "#586e75"
hyperlink_color = "#839496"
warn_fg_color = "#839496"
error_fg_color = "#839496"
