extreme_bg_color = "#f8b195"
faint_bg_color = "#f67280"
code_bg_color = "#c06c84"
panel_fill = "#6c5b7b"
window_fill = "#355c7d"
window_stroke_color = "#586e75"
hyperlink_color = "#839496"
warn_fg_color = "#839496"
error_fg_color = "#839496"
