extreme_bg_color = "#d1e751"
faint_bg_color = "#ffffff"
code_bg_color = "#000000"
panel_fill = "#4dbce9"
window_fill = "#26ade4"
window_stroke_color = "#586e75"
hyperlink_color = "#839496"
warn_fg_color = "#839496"
error_fg_color = "#839496"
