extreme_bg_color = "#5e412f"
faint_bg_color = "#fcebb6"
code_bg_color = "#78c0a8"
panel_fill = "#f07818"
window_fill = "#f0a830"
window_stroke_color = "#586e75"
hyperlink_color = "#839496"
warn_fg_color = "#839496"
error_fg_color = "#839496"
