extreme_bg_color = "#eee6ab"
faint_bg_color = "#c5bc8e"
code_bg_color = "#696758"
panel_fill = "#45484b"
window_fill = "#36393b"
window_stroke_color = "#586e75"
hyperlink_color = "#839496"
warn_fg_color = "#839496"
error_fg_color = "#839496"
