extreme_bg_color = "#b3cc57"
faint_bg_color = "#ecf081"
code_bg_color = "#ffbe40"
panel_fill = "#ef746f"
window_fill = "#ab3e5b"
window_stroke_color = "#586e75"
hyperlink_color = "#839496"
warn_fg_color = "#839496"
error_fg_color = "#839496"
