extreme_bg_color = "#67917a"
faint_bg_color = "#170409"
code_bg_color = "#b8af03"
panel_fill = "#ccbf82"
window_fill = "#e33258"
window_stroke_color = "#586e75"
hyperlink_color = "#839496"
warn_fg_color = "#839496"
error_fg_color = "#839496"
