extreme_bg_color = "#aab3ab"
faint_bg_color = "#c4cbb7"
code_bg_color = "#ebefc9"
panel_fill = "#eee0b7"
window_fill = "#e8caaf"
window_stroke_color = "#586e75"
hyperlink_color = "#839496"
warn_fg_color = "#839496"
error_fg_color = "#839496"
