extreme_bg_color = "#e8d5b7"
faint_bg_color = "#0e2430"
code_bg_color = "#fc3a51"
panel_fill = "#f5b349"
window_fill = "#e8d5b9"
window_stroke_color = "#586e75"
hyperlink_color = "#839496"
warn_fg_color = "#839496"
error_fg_color = "#839496"
