extreme_bg_color = "#607848"
faint_bg_color = "#789048"
code_bg_color = "#c0d860"
panel_fill = "#f0f0d8"
window_fill = "#604848"
window_stroke_color = "#586e75"
hyperlink_color = "#839496"
warn_fg_color = "#839496"
error_fg_color = "#839496"
