extreme_bg_color = "#3e4147"
faint_bg_color = "#fffedf"
code_bg_color = "#dfba69"
panel_fill = "#5a2e2e"
window_fill = "#2a2c31"
window_stroke_color = "#586e75"
hyperlink_color = "#839496"
warn_fg_color = "#839496"
error_fg_color = "#839496"
