extreme_bg_color = "#fc354c"
faint_bg_color = "#29221f"
code_bg_color = "#13747d"
panel_fill = "#0abfbc"
window_fill = "#fcf7c5"
window_stroke_color = "#586e75"
hyperlink_color = "#839496"
warn_fg_color = "#839496"
error_fg_color = "#839496"
