extreme_bg_color = "#1c2130"
faint_bg_color = "#028f76"
code_bg_color = "#b3e099"
panel_fill = "#ffeaad"
window_fill = "#d14334"
window_stroke_color = "#586e75"
hyperlink_color = "#839496"
warn_fg_color = "#839496"
error_fg_color = "#839496"
