extreme_bg_color = "#a7c5bd"
faint_bg_color = "#e5ddcb"
code_bg_color = "#eb7b59"
panel_fill = "#cf4647"
window_fill = "#524656"
window_stroke_color = "#586e75"
hyperlink_color = "#839496"
warn_fg_color = "#839496"
error_fg_color = "#839496"
