extreme_bg_color = "#dad6ca"
faint_bg_color = "#1bb0ce"
code_bg_color = "#4f8699"
panel_fill = "#6a5e72"
window_fill = "#563444"
window_stroke_color = "#586e75"
hyperlink_color = "#839496"
warn_fg_color = "#839496"
error_fg_color = "#839496"
