window_stroke_color = "#586e75ff"
hyperlink_color = "#839496ff"
warn_fg_color = "#839496ff"
extreme_bg_color = "#a59a74ff"
panel_fill = "#6a5e72ff"
code_bg_color = "#f3dec9ff"
faint_bg_color = "#546c74ff"
error_fg_color = "#839496ff"
window_fill = "#563444ff"
