extreme_bg_color = "#5c323e"
faint_bg_color = "#a82743"
code_bg_color = "#e15e32"
panel_fill = "#c0d23e"
window_fill = "#e5f04c"
window_stroke_color = "#586e75"
hyperlink_color = "#839496"
warn_fg_color = "#839496"
error_fg_color = "#839496"
