extreme_bg_color = "#fdf1cc"
faint_bg_color = "#c6d6b8"
code_bg_color = "#987f69"
panel_fill = "#e3ad40"
window_fill = "#fcd036"
window_stroke_color = "#586e75"
hyperlink_color = "#839496"
warn_fg_color = "#839496"
error_fg_color = "#839496"
