extreme_bg_color = "#230f2b"
faint_bg_color = "#f21d41"
code_bg_color = "#ebebbc"
panel_fill = "#bce3c5"
window_fill = "#82b3ae"
window_stroke_color = "#586e75"
hyperlink_color = "#839496"
warn_fg_color = "#839496"
error_fg_color = "#839496"
