extreme_bg_color = "#b9d3b0"
faint_bg_color = "#81bda4"
code_bg_color = "#b28774"
panel_fill = "#f88f79"
window_fill = "#f6aa93"
window_stroke_color = "#586e75"
hyperlink_color = "#839496"
warn_fg_color = "#839496"
error_fg_color = "#839496"
