extreme_bg_color = "#1c0113"
faint_bg_color = "#6b0103"
code_bg_color = "#a30006"
panel_fill = "#c21a01"
window_fill = "#f03c02"
window_stroke_color = "#586e75"
hyperlink_color = "#839496"
warn_fg_color = "#839496"
error_fg_color = "#839496"
