extreme_bg_color = "#e3dfba"
faint_bg_color = "#c8d6bf"
code_bg_color = "#93ccc6"
panel_fill = "#6cbdb5"
window_fill = "#1a1f1e"
window_stroke_color = "#586e75"
hyperlink_color = "#839496"
warn_fg_color = "#839496"
error_fg_color = "#839496"
