extreme_bg_color = "#c1b398"
faint_bg_color = "#605951"
code_bg_color = "#fbeec2"
panel_fill = "#61a6ab"
window_fill = "#accec0"
window_stroke_color = "#586e75"
hyperlink_color = "#839496"
warn_fg_color = "#839496"
error_fg_color = "#839496"
