extreme_bg_color = "#413d3d"
faint_bg_color = "#040004"
code_bg_color = "#c8ff00"
panel_fill = "#fa023c"
window_fill = "#4b000f"
window_stroke_color = "#586e75"
hyperlink_color = "#839496"
warn_fg_color = "#839496"
error_fg_color = "#839496"
