extreme_bg_color = "#ffefd3"
faint_bg_color = "#fffee4"
code_bg_color = "#d0ecea"
panel_fill = "#9fd6d2"
window_fill = "#8b7a5e"
window_stroke_color = "#586e75"
hyperlink_color = "#839496"
warn_fg_color = "#839496"
error_fg_color = "#839496"
