extreme_bg_color = "#cfffdd"
faint_bg_color = "#b4dec1"
code_bg_color = "#5c5863"
panel_fill = "#a85163"
window_fill = "#ff1f4c"
window_stroke_color = "#586e75"
hyperlink_color = "#839496"
warn_fg_color = "#839496"
error_fg_color = "#839496"
