extreme_bg_color = "#9dc9ac"
faint_bg_color = "#fffec7"
code_bg_color = "#f56218"
panel_fill = "#ff9d2e"
window_fill = "#919167"
window_stroke_color = "#586e75"
hyperlink_color = "#839496"
warn_fg_color = "#839496"
error_fg_color = "#839496"
