extreme_bg_color = "#4e395d"
faint_bg_color = "#827085"
code_bg_color = "#8ebe94"
panel_fill = "#ccfc8e"
window_fill = "#dc5b3e"
window_stroke_color = "#586e75"
hyperlink_color = "#839496"
warn_fg_color = "#839496"
error_fg_color = "#839496"
