extreme_bg_color = "#a8a7a7"
faint_bg_color = "#cc527a"
code_bg_color = "#e8175d"
panel_fill = "#474747"
window_fill = "#363636"
window_stroke_color = "#586e75"
hyperlink_color = "#839496"
warn_fg_color = "#839496"
error_fg_color = "#839496"
