extreme_bg_color = "#00a0b0"
faint_bg_color = "#6a4a3c"
code_bg_color = "#cc333f"
panel_fill = "#eb6841"
window_fill = "#edc951"
window_stroke_color = "#586e75"
hyperlink_color = "#839496"
warn_fg_color = "#839496"
error_fg_color = "#839496"
