panel_fill = "#9d9d93ff"
hyperlink_color = "#839496ff"
warn_fg_color = "#839496ff"
extreme_bg_color = "#f8edd1ff"
window_fill = "#c5cfc6ff"
error_fg_color = "#839496ff"
window_stroke_color = "#586e75ff"
code_bg_color = "#474843ff"
faint_bg_color = "#d88a8aff"
