extreme_bg_color = "#f8edd1"
faint_bg_color = "#d88a8a"
code_bg_color = "#474843"
panel_fill = "#9d9d93"
window_fill = "#c5cfc6"
window_stroke_color = "#586e75"
hyperlink_color = "#839496"
warn_fg_color = "#839496"
error_fg_color = "#839496"
