extreme_bg_color = "#f38a8a"
faint_bg_color = "#55443d"
code_bg_color = "#a0cab5"
panel_fill = "#cde9ca"
window_fill = "#f1edd0"
window_stroke_color = "#586e75"
hyperlink_color = "#839496"
warn_fg_color = "#839496"
error_fg_color = "#839496"
