extreme_bg_color = "#ff003c"
faint_bg_color = "#ff8a00"
code_bg_color = "#fabe28"
panel_fill = "#88c100"
window_fill = "#00c176"
window_stroke_color = "#586e75"
hyperlink_color = "#839496"
warn_fg_color = "#839496"
error_fg_color = "#839496"
