extreme_bg_color = "#4d3b3b"
faint_bg_color = "#de6262"
code_bg_color = "#ffb88c"
panel_fill = "#ffd0b3"
window_fill = "#f5e0d3"
window_stroke_color = "#586e75"
hyperlink_color = "#839496"
warn_fg_color = "#839496"
error_fg_color = "#839496"
