extreme_bg_color = "#fffbb7"
faint_bg_color = "#a6f6af"
code_bg_color = "#66b6ab"
panel_fill = "#5b7c8d"
window_fill = "#4f2958"
window_stroke_color = "#586e75"
hyperlink_color = "#839496"
warn_fg_color = "#839496"
error_fg_color = "#839496"
