extreme_bg_color = "#e94e77"
faint_bg_color = "#d68189"
code_bg_color = "#c6a49a"
panel_fill = "#c6e5d9"
window_fill = "#f4ead5"
window_stroke_color = "#586e75"
hyperlink_color = "#839496"
warn_fg_color = "#839496"
error_fg_color = "#839496"
