extreme_bg_color = "#edf6ee"
faint_bg_color = "#d1c089"
code_bg_color = "#b3204d"
panel_fill = "#412e28"
window_fill = "#151101"
window_stroke_color = "#586e75"
hyperlink_color = "#839496"
warn_fg_color = "#839496"
error_fg_color = "#839496"
