extreme_bg_color = "#9d7e79"
faint_bg_color = "#ccac95"
code_bg_color = "#9a947c"
panel_fill = "#748b83"
window_fill = "#5b756c"
window_stroke_color = "#586e75"
hyperlink_color = "#839496"
warn_fg_color = "#839496"
error_fg_color = "#839496"
