extreme_bg_color = "#30261c"
faint_bg_color = "#403831"
code_bg_color = "#36544f"
panel_fill = "#1f5f61"
window_fill = "#0b8185"
window_stroke_color = "#586e75"
hyperlink_color = "#839496"
warn_fg_color = "#839496"
error_fg_color = "#839496"
