extreme_bg_color = "#d1313d"
faint_bg_color = "#e5625c"
code_bg_color = "#f9bf76"
panel_fill = "#8eb2c5"
window_fill = "#615375"
window_stroke_color = "#586e75"
hyperlink_color = "#839496"
warn_fg_color = "#839496"
error_fg_color = "#839496"
