extreme_bg_color = "#ffe181"
faint_bg_color = "#eee9e5"
code_bg_color = "#fad3b2"
panel_fill = "#ffba7f"
window_fill = "#ff9c97"
window_stroke_color = "#586e75"
hyperlink_color = "#839496"
warn_fg_color = "#839496"
error_fg_color = "#839496"
