extreme_bg_color = "#73c8a9"
faint_bg_color = "#dee1b6"
code_bg_color = "#e1b866"
panel_fill = "#bd5532"
window_fill = "#373b44"
window_stroke_color = "#586e75"
hyperlink_color = "#839496"
warn_fg_color = "#839496"
error_fg_color = "#839496"
