window_fill = "#fcf7d3ff"
extreme_bg_color = "#eaa287ff"
code_bg_color = "#3d502bff"
window_stroke_color = "#586e75ff"
panel_fill = "#899074ff"
warn_fg_color = "#839496ff"
hyperlink_color = "#839496ff"
error_fg_color = "#839496ff"
faint_bg_color = "#cd8c52ff"
