window_stroke_color = "#586e75ff"
error_fg_color = "#839496ff"
extreme_bg_color = "#42423fff"
code_bg_color = "#0cbeb4ff"
faint_bg_color = "#c7d6b2ff"
hyperlink_color = "#839496ff"
window_fill = "#1c322eff"
warn_fg_color = "#839496ff"
panel_fill = "#6cbdb5ff"
