window_fill = "#52bdacff"
panel_fill = "#75f2e6ff"
warn_fg_color = "#839496ff"
window_stroke_color = "#586e75ff"
code_bg_color = "#155853ff"
extreme_bg_color = "#94a2a7ff"
error_fg_color = "#839496ff"
faint_bg_color = "#c7d6b2ff"
hyperlink_color = "#839496ff"
