code_bg_color = "#000000ff"
extreme_bg_color = "#e89facff"
faint_bg_color = "#f4d5d7ff"
window_fill = "#f4ead5ff"
error_fg_color = "#839496ff"
warn_fg_color = "#839496ff"
window_stroke_color = "#586e75ff"
hyperlink_color = "#839496ff"
panel_fill = "#c6e5d9ff"
