panel_fill = "#bce3c5ff"
window_stroke_color = "#586e75ff"
extreme_bg_color = "#230f2bff"
error_fg_color = "#839496ff"
hyperlink_color = "#839496ff"
code_bg_color = "#ebebbcff"
faint_bg_color = "#d55f69ff"
window_fill = "#82b3aeff"
warn_fg_color = "#839496ff"
