extreme_bg_color = "#c99f56ff"
hyperlink_color = "#839496ff"
faint_bg_color = "#d55f69ff"
window_fill = "#82b3aeff"
code_bg_color = "#080726ff"
error_fg_color = "#839496ff"
window_stroke_color = "#586e75ff"
panel_fill = "#bce3c5ff"
warn_fg_color = "#839496ff"
