window_stroke_color = "#586e75ff"
code_bg_color = "#000000ff"
error_fg_color = "#839496ff"
faint_bg_color = "#f4fad2ff"
warn_fg_color = "#839496ff"
panel_fill = "#4b532cff"
window_fill = "#f0f2ebff"
extreme_bg_color = "#ff9e9eff"
hyperlink_color = "#839496ff"
