error_fg_color = "#839496ff"
window_stroke_color = "#586e75ff"
window_fill = "#4e2319ff"
code_bg_color = "#ffffffff"
panel_fill = "#754d2dff"
hyperlink_color = "#839496ff"
warn_fg_color = "#839496ff"
extreme_bg_color = "#655643ff"
faint_bg_color = "#837700ff"
