hyperlink_color = "#839496ff"
code_bg_color = "#ffffffff"
extreme_bg_color = "#655643ff"
window_fill = "#7d4338ff"
error_fg_color = "#839496ff"
warn_fg_color = "#839496ff"
faint_bg_color = "#558d77ff"
window_stroke_color = "#586e75ff"
panel_fill = "#a58b15ff"
