extreme_bg_color = "#0049a8"
faint_bg_color = "#1d44b8k"
code_bg_color = "#0049a8"
panel_fill = "#f09c0c"
window_fill = "#d67c1c"
window_stroke_color = "#f7f7f7"
hyperlink_color = "#f7f7f7"
warn_fg_color = "#f7f7f7"
error_fg_color = "#f7f7f7"