extreme_bg_color = "#002b36"
faint_bg_color = "#073642"
code_bg_color = "#073642"
panel_fill = "#073642"
window_fill = "#073642"
window_stroke_color = "#586e75"
hyperlink_color = "#839496"
warn_fg_color = "#839496"
error_fg_color = "#839496"