panel_fill = "#ff834cff"
hyperlink_color = "#839496ff"
faint_bg_color = "#309292ff"
window_stroke_color = "#586e75ff"
warn_fg_color = "#839496ff"
error_fg_color = "#839496ff"
code_bg_color = "#ffffffff"
window_fill = "#779639ff"
extreme_bg_color = "#046d8bff"
