error_fg_color = "#839496ff"
window_stroke_color = "#586e75ff"
warn_fg_color = "#839496ff"
panel_fill = "#e84a5fff"
code_bg_color = "#ffffffff"
hyperlink_color = "#839496ff"
faint_bg_color = "#a5799eff"
window_fill = "#2a363bff"
extreme_bg_color = "#849983ff"
