faint_bg_color = "#6a406aff"
window_fill = "#f07241ff"
code_bg_color = "#fffeffff"
window_stroke_color = "#586e75ff"
error_fg_color = "#839496ff"
extreme_bg_color = "#300030ff"
hyperlink_color = "#839496ff"
warn_fg_color = "#839496ff"
panel_fill = "#c04848ff"
