panel_fill = "#5d0707ff"
faint_bg_color = "#6a406aff"
window_stroke_color = "#586e75ff"
hyperlink_color = "#839496ff"
code_bg_color = "#fffeffff"
extreme_bg_color = "#300030ff"
error_fg_color = "#839496ff"
window_fill = "#f07241ff"
warn_fg_color = "#839496ff"
