code_bg_color = "#000000ff"
window_fill = "#e1f5c4ff"
window_stroke_color = "#586e75ff"
panel_fill = "#6b5341ff"
hyperlink_color = "#839496ff"
faint_bg_color = "#d88a59ff"
extreme_bg_color = "#ce7373ff"
error_fg_color = "#839496ff"
warn_fg_color = "#839496ff"
