hyperlink_color = "#839496ff"
window_stroke_color = "#586e75ff"
error_fg_color = "#839496ff"
panel_fill = "#6b5341ff"
faint_bg_color = "#d88a59ff"
warn_fg_color = "#839496ff"
code_bg_color = "#000000ff"
extreme_bg_color = "#ce7373ff"
window_fill = "#e5c3acff"
