window_stroke_color = "#586e75ff"
faint_bg_color = "#6aad60ff"
code_bg_color = "#ffffffff"
error_fg_color = "#839496ff"
extreme_bg_color = "#8d9b60ff"
panel_fill = "#ef746fff"
window_fill = "#a34a90ff"
hyperlink_color = "#839496ff"
warn_fg_color = "#839496ff"
