warn_fg_color = "#839496ff"
window_fill = "#ba9266ff"
faint_bg_color = "#8f967fff"
panel_fill = "#777673ff"
error_fg_color = "#839496ff"
extreme_bg_color = "#aab3abff"
window_stroke_color = "#586e75ff"
hyperlink_color = "#839496ff"
code_bg_color = "#ffffffff"
