error_fg_color = "#839496ff"
hyperlink_color = "#839496ff"
panel_fill = "#a37800ff"
window_stroke_color = "#586e75ff"
warn_fg_color = "#839496ff"
code_bg_color = "#000000ff"
extreme_bg_color = "#fdf1ccff"
faint_bg_color = "#c6d6b8ff"
window_fill = "#fcd036ff"
