code_bg_color = "#000201ff"
error_fg_color = "#839496ff"
faint_bg_color = "#bfced0ff"
warn_fg_color = "#839496ff"
extreme_bg_color = "#cacacaff"
hyperlink_color = "#839496ff"
window_fill = "#e6f9bcff"
panel_fill = "#bcdea5ff"
window_stroke_color = "#586e75ff"
