window_stroke_color = "#586e75ff"
warn_fg_color = "#839496ff"
hyperlink_color = "#839496ff"
panel_fill = "#a59eaaff"
extreme_bg_color = "#b8aa79ff"
window_fill = "#8f4e6eff"
code_bg_color = "#000000ff"
error_fg_color = "#839496ff"
faint_bg_color = "#57808cff"
