error_fg_color = "#839496ff"
window_fill = "#421818ff"
extreme_bg_color = "#000000ff"
hyperlink_color = "#839496ff"
warn_fg_color = "#839496ff"
code_bg_color = "#fffbfbff"
faint_bg_color = "#fb7478ff"
window_stroke_color = "#586e75ff"
panel_fill = "#0c111eff"
