hyperlink_color = "#839496ff"
window_stroke_color = "#586e75ff"
extreme_bg_color = "#000000ff"
window_fill = "#520000ff"
warn_fg_color = "#839496ff"
code_bg_color = "#fffbfbff"
faint_bg_color = "#833e40ff"
error_fg_color = "#839496ff"
panel_fill = "#0c111eff"
