window_stroke_color = "#586e75ff"
warn_fg_color = "#839496ff"
panel_fill = "#0c111eff"
code_bg_color = "#fffbfbff"
extreme_bg_color = "#000000ff"
hyperlink_color = "#839496ff"
faint_bg_color = "#fb7478ff"
window_fill = "#520000ff"
error_fg_color = "#839496ff"
