extreme_bg_color = "#000000ff"
hyperlink_color = "#839496ff"
faint_bg_color = "#833e40ff"
warn_fg_color = "#839496ff"
window_stroke_color = "#586e75ff"
panel_fill = "#ba3c3cff"
error_fg_color = "#839496ff"
code_bg_color = "#fffbfbff"
window_fill = "#520000ff"
