window_fill = "#b05574ff"
panel_fill = "#35256cff"
warn_fg_color = "#839496ff"
code_bg_color = "#f9d5bcff"
error_fg_color = "#839496ff"
hyperlink_color = "#839496ff"
faint_bg_color = "#000000ff"
window_stroke_color = "#586e75ff"
extreme_bg_color = "#5e9fa3ff"
